# Generated by Django 5.0.7 on 2024-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_duration', models.IntegerField(help_text='Duration in months')),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed')], max_length=50)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
            },
        ),
    ]
