# Generated by Django 5.0.7 on 2024-12-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_loanapplicationforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationforms',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
