# Generated by Django 5.0.7 on 2024-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_loanapplicationforms_options_employeragreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='name',
            field=models.CharField(default='piustest', max_length=100),
            preserve_default=False,
        ),
    ]
